### ISSUE TITLE
When will we release Kweb 1.0?

### ISSUE THREAD

**Issue by alkoclick** [kwebio/kweb-core#138]
What do we need to get Kweb to version 1.0? What are the goals, expectations, roadmap?

**Comment by sanity** [comment]
I think once I'm fairly confident that the API is stable because I don't think we should make breaking API changes after 1.0 (although deprecation is fine).  

It's been great to get your feedback and others, but I think we'll need more people using it to work out where the remaining shortcomings might be - my gut says we still have a few.

Probably the biggest architectural change that I'd like to see before 1.0 is #53.  It should significantly improve efficiency (by avoiding use of [eval](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval), while also simplifying Kweb's implementation - because it will make [instructions](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/client/Server2ClientMessage.kt#L11) obsolete along with their related code.

My philosophy with Kweb has always been to take my time and try to do it right, and that's also my feeling on a 1.0 release, but I'm open to arguments if, for example, you think the absence of a 1.0.0 release is hurting adoption.

Just as a benchmark, it took Ktor about 4 years to get to its 1.0.0 release, while it's been about 3 years since Kweb's first release.  Obviously that's not a basis to decide when to release - but I think it shows that Kweb hasn't been slow relative to other comparable libraries.

May I ask why you ask?

**Comment by alkoclick** [comment]
> May I ask why you ask?

No particular reason, just trying to understand the philosophy and goals. I think it'd be cool to get a roadmap down, so we can figure out what the relative priorities are and it's also nice to have clear, achievable targets.

One thing that I have seen the CNCF projects do very successfully, is to set a very clear set of objectives about goals and non-goals. Who is the target audience for Kweb? Who isn't? Then we can see about making their use cases better.

> you think the absence of a 1.0.0 release is hurting adoption

Have no data on that, though I could see it being true.

My overall feel about Kweb is that it's a great idea, packing a lot of really smart concepts, but the code is not optimal and in some places, sub-optimal. 

Personally, I have been looking for this product for years. Others have too, which is why Vaadin is still a thing. I would love to see Kweb grow into that space because I think it massively empowers backenders to make pretty websites with minimal fuss

**Comment by sanity** [comment]
For me a 1.0 release is mostly about saying "this API won't change", and it's hard to enumerate exactly what it will take to get to that point - probably more of a judgement call than ticking a specific set of feature boxes.

I don't feel a sense of urgency to release 1.0, rather I think it's important to take our time and get it right.  I think we're moving in the right direction with every commit though.

Setting explicit priorities in a volunteer-run project doesn't necessarily impact what actually gets worked on - as most people tend to work on whatever aspect of the project is important or interesting to them.

That said, it might be a good idea to designate some issues as "1.0 blockers" using a label - such that if someone is interested in working on Kweb but isn't sure what they want to do, this will provide some direction.

> Personally, I have been looking for this product for years. Others have too, which is why Vaadin is still a thing. I would love to see Kweb grow into that space because I think it massively empowers backenders to make pretty websites with minimal fuss

Agreed, I built my first website sometime around 1996 and many since - and it's not clear to me that the tooling is moving in a good direction.  Rather it just seems to get more complicated without getting any better.

Kweb is an attempt at a fresh start, leaving behind the unhelpful dogmas that have become rather engrained over the years.  It still needs work, obviously, but I'm increasingly confident that the broad approach is correct.
