### ISSUE TITLE
Restrictive License

### ISSUE THREAD

**Issue by fabiocmazzo** [kwebio/kweb-core#153]
I thought this project is fantastic.

But I come to speak with all due respect - I know that it is a decision that is not up to anyone but you only - but a restrictive license like the GPL for a framework can drastically decrease its adoption.

I understand that the GPL can be important when it comes to products "ready" to be used (Like da database, MessageBroker, etc) . But I am uncomfortable about starting a commercial project with a GPL framework and the license "contaminating" my product code.

Note an example like Java, that the license is restrictive, but has the classpath exception, where all the code inside the classpath does not need to follow the license.

I strongly believe that the framework would be more successful as a more permissive license like Apache, BSD or MIT.

Thank you,

**Comment by sanity** [comment]
Hi, I think there may be a misunderstanding because Kweb is [released](https://github.com/kwebio/kweb-core/blob/master/LICENSE) under the GNU *Lesser* General Public License (LGPL), which is much less restrictive than the GPL license, and is frequently used for libraries because it places no restrictions on code that uses the library (unlike the GPL).

An exception is the [kweb-template](https://github.com/kwebio/kweb-template) library which is public domain.

Please let me know if this resolves your concern.
