### ISSUE TITLE
Utility to convert HTML fragment to Kweb code

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#217]
Should be easy enough using [JSoup](https://jsoup.org/cookbook/input/parse-body-fragment). Ideally it could be made available online, similar to https://jsonformatter.curiousconcept.com/.

**Comment by chucky2002** [comment]
That would be a great feature. I am currently working on optimizing the loading of HTML pages so that the browser uses CPU resources for rendering as late as possible.

I am currently working with the workaround of setting style="display:none" when creating the table and only changing to style="" after the complete table has been created.

A possibility to work with "HTML Fragement" would make this easier.

Translated with DeepL.com (free version)
