### ISSUE TITLE
Enhance routing path syntax to support URL queries

### ISSUE THREAD

**Issue by kokorins** [kwebio/kweb-core#233]
**Is your feature request related to a problem? Please describe.**
I'm trying to get external link working with additional arguments something like:
```
/callback?arg=value
```
Is I've been looking through the code there is no way to get those url arguments as parameters in routing path:
`path("/callback?{}")` wont work as there is check for split by `/`

**Describe the solution you'd like**
`params` of `PathReceiver` should contain arguments of an url as well as template elements.

**Describe alternatives you've considered**
`path("/something/{callback}")` will preserve only `callback` without additional arguments.

**Additional context**
kweb/routing/UrlToPathSegmentsRF.kt
```
override fun invoke(from: String): List<String> {
    return from.substringBefore('?').split('/').drop(1)
}
```

**Comment by sanity** [comment]
You can use [WebBrowser.gurl](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/WebBrowser.kt#L338) to obtain the full URL then extract the query:

```kotlin
    route {
        path("/") {
            render(gurl.query) { query ->
                p().text("Query: $query")
            }
            // or more simply
            p().text(gurl.query.map {"Query: $it"})
        }
     }
```

Let me know if that solves your problem.

I'll leave this open as an enhancement because it would be nice to extend the routing template syntax to support paths like these:

`path("/something/{query}"`
`path("/something/user={user}"`
