### ISSUE TITLE
[FR] Extract messaging and routing behaviors to interface, to allow writing adapters for different frameworks

### ISSUE THREAD

**Issue by GavinRay97** [kwebio/kweb-core#272]
I'd like to add support for using Kweb with Quarkus.

A quick search through the code shows direct Ktor usage in a number of files, but nothing that looks too crazy:

![image](https://user-images.githubusercontent.com/26604994/165984178-25957870-1340-4e17-a4b1-454587fef5b2.png)

If someone were interested in extracting these implementations out into interfaces, how much effort would that be and where would one start?

Thank you (super neat project, by the way!) 🙂

**Comment by sanity** [comment]
Thank you for the compliment :)

I think abstracting out the HTTP framework should be fairly doable, most of the Ktor-specific stuff is in [Kweb.kt](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/Kweb.kt), also a little in [HttpRequestInfo.kt](https://github.com/kwebio/kweb-core/blob/master/src/main/kotlin/kweb/client/HttpRequestInfo.kt).

Happy to answer any other questions.

**Comment by BenjaminFaal** [comment]
@sanity @GavinRay97 i got Spring Boot working, see https://github.com/kwebio/kweb-core/pull/340

When i try the same in Quarkus the HTML response partially loads but the browser keeps loading because the response is never flushed/closed from the server. When i remove the asyncSupported parameter from the @WebServlet annotation the HTML response loads but the WebSocket does not work. Because of this: https://github.com/ktorio/ktor/blob/928d405b06b455ec6e49118a24535a806693b09b/ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/BlockingServlet.kt#L80
