### ISSUE TITLE
Client updates are inconstant with duplicated tabs

### ISSUE THREAD

**Issue by arocnies** [kwebio/kweb-core#28]
#### Configuration:
  Chrome: Version 56.0.2924.87 (64-bit)
  Linux (Ubuntu 16.04)

When running the example from [your-first-kwebsite](http://kweb.io/use/your-first-kwebsite.html) I noticed that multiple browser tabs accessing the kweb server behave differently depending on if they navigated to the URL or if they were created using "Right-click -> Duplicate" in chrome.

#### URL navigated tabs behavior:
- Each tab updates the server's count val.
- The h1 text is updated on each click.

#### Duplicate tabs behavior:
- First tab behaves as expected on its own.
- When the second tab is made using "Right-click -> Duplicate", it displays the count at the time it was duplicated. Clicking the second tab **updates the first tab's count** but **does not update its own count**.

## Steps to reproduce:
- Run the example
- Open a second tab and navigate to the example URL
- Observe each tab responding to being clicked

- Remove one tab
- Duplicate the remaining tab by right clicking the tab and selecting "Duplicate"
- Observe the original tab responding to both tabs being clicked
- Observe the duplicate tab not responding to either tab being clicked

I figure this issue is low severity since kweb is only in alpha. This may have some crossover with #2

**Comment by sanity** [comment]
Hmm, interesting, I don't seem to have that Duplicate option on my Mac Chrome (58.0.3029.110 (64-bit).

But it seems like it might duplicate the DOM (rather than pulling down a new page), which probably would confuse Kweb right now :)

What is the purpose of this Duplicate option?  Is it a developer tool?

**Comment by ethanmdavidson** [comment]
This is actually a bug in the your-first-kwebsite example, and you'll see the same behavior if you open the example in two tabs (even if you don't use the duplicate button). I think it's because the example doesn't use a KVar for the count, so it doesn't cause the dom to re-render when the value changes. If you rewrite the example like this it works correctly across two tabs:

```kotlin
fun main(args: Array<String>) {
    val count = KVar(0)

    Kweb(port = 8080) {
        doc.body.new {
            h1().text(count.map{ c -> "Count: $c"})
            button().text("Click me!").on.click {
                count.value += 1
            }
        }
    }
}
```

There is a bug in this code but it's a different problem (and not related to this example) so I'll open a new issue.

@sanity the your-first-kwebsite example doesn't seem to be in the docs anymore, do you want me to fit it in somewhere or should we just close this?

**Comment by sanity** [comment]
Oh, yes - that's some old example code - I think we can just remove it and close it (unless you think the docs would benefit from an example like this).

**Comment by ethanmdavidson** [comment]
No, I think the basics of binding are covered well enough by https://github.com/kwebio/kweb-docs/blob/master/state.rst#binding-a-kvar-to-an-input-elements-value

However, i do think we need a demo with all sorts of different controls and bindings. I'll try and put something together.

**Comment by sanity** [comment]
@ethanmdavidson That would be great.  There was an old `kweb-demo` repo which I deleted, you're welcome to recreate that if you'd like to use it.

**Comment by sanity** [comment]
@ethanmdavidson By the way, if you do a new demo I'd be happy to replace http://demo.kweb.io:7659/ with it (it's running on a cheap EC2 instance).  Currently it must be updated manually.
