### ISSUE TITLE
Write "Integrations" page discussing Ktor and other systems that work well with Kweb 

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#380]
From the Matrix chat room:

> i guess buildPage in this page is the obsolete API. https://docs.kweb.io/book/integrations.html I found this variable... https://github.com/kwebio/kweb-core/blob/6c9f7a126f6cb83daa786441c25239822af78269/src/main/kotlin/kweb/KtorFeature.kt#L58-L66

> But i can't understand how should i use the recommended style

I'm not really familiar with this code so unsure what he should be doing here.

**Comment by sanity** [comment]
cc: @alkoclick I think you wrote this, would you mind taking a look?

**Comment by alkoclick** [comment]
## Short answer

Just remove the buildpage from the constructor call, then add a routing block (available using`import io.ktor.server.routing.*`)
```
    application.install(Kweb) { }
    routing {
        get("/{visitedUrl...}") {
            call.respondKwebRender { 
                buildPage
            }
        }
    }
```

## Longer answer

Oof, this is quite a blast from the past.

Using the inline buildpage syntax, in the way that [the integrations example](https://docs.kweb.io/book/integrations.html) demonstrates is pretty problematic imo, because it doesn't scale to anything that isn't a demo example, especially for Ktor consumers. One of the main issues is how to set up Ktor authentication (or any other Ktor behavior) on specific sub routes, which becomes nearly impossible. This would force a user to do routing completely in Ktor, rather than Kweb. When doing routing in Ktor, you use the [Ktor routing plugin](https://ktor.io/docs/routing-in-ktor.html#install_plugin) which is available from the ktor-server-core artifact. This is what this replacement code corresponds to.

This was the primary logic, when I wrote this, 3 years ago. Note that there is a non-trivial design change implied here: Using Ktor routing can break with the SPA design that Kweb is primarily trying to promote and have actual page reloads when navigating to different routes.

P.S: Note that the example is delibaretly not using the IDEA/Kotlin drop-in code replacement annotation, because that could not at the time (not sure about atm) replace a code block with a higher level one (meaning outside its function call), which is what is needed here.

**Comment by alkoclick** [comment]
## Short answer

Just remove the buildpage from the constructor call, then add a routing block (available using`import io.ktor.server.routing.*`)
```
    application.install(Kweb) { }
    routing {
        get("/{visitedUrl...}") {
            call.respondKwebRender { 
                buildPage
            }
        }
    }
```

## Longer answer

Oof, this is quite a blast from the past.

Using the inline buildpage syntax, in the way that [the integrations example](https://docs.kweb.io/book/integrations.html) demonstrates is pretty problematic imo, because it doesn't scale to anything that isn't a demo example, especially for Ktor consumers. One of the main issues is how to set up Ktor authentication (or any other Ktor behavior) on specific sub routes, which becomes nearly impossible. This would force a user to do routing completely in Ktor, rather than Kweb. When doing routing in Ktor, you use the [Ktor routing plugin](https://ktor.io/docs/routing-in-ktor.html#install_plugin) which is available from the ktor-server-core artifact. This is what this replacement code corresponds to.

This was the primary logic, when I wrote this, 3 years ago. Note that there is a non-trivial design change implied here: Using Ktor routing can break with the SPA design that Kweb is primarily trying to promote and have actual page reloads when navigating to different routes.

P.S: Note that the example is delibaretly not using the IDEA/Kotlin drop-in code replacement annotation, because that could not at the time (not sure about atm) replace a code block with a higher level one (meaning outside its function call), which is what is needed here.

**Comment by sanity** [comment]
@alkoclick Many thanks.

It sounds like the problems only arise if you try using Ktor functionality like auth in conjunction with Kweb (which probably needs to handle its own auth)?

I don't want to lead people astray with the user manual so if this solution has issues I can remove [that part](https://docs.kweb.io/book/integrations.html#spring-boot), what do you think?

**Comment by alkoclick** [comment]
Generally if you install Kweb as a Ktor feature, chances are imo that any non-trivial setup will want to do routing via Ktor. As a result, I'd recommend replacing the usage of the buildpage argument with the codeblock I also posted above. 

If that's not a pattern you want to encourage in the docs, then maybe it'd be best to drop a note that this is a setup for simple pages that don't want to use a lot of Ktor functionality

**Comment by sanity** [comment]
I've removed the Integrations page for now as it seems like it was probably doing more harm than good, repurposing this issue to rewrite it.
