### ISSUE TITLE
Enable TLS and HTTPS with Ktor-Access

### ISSUE THREAD

**Issue by rpanic** [kwebio/kweb-core#60]
Currently, there is no way to give Ktor options for Ktor-specific settings like SSL certificates and SSL ports, since these options have to be handed to Ktor before starting the Jetty server. 
To implement this, probably a Kweb-Configuration workflow would be needed to configure Ktor without exposing too much.

**Comment by sanity** [comment]
Doing some refactoring on Kweb class, will try to address this in the process: https://github.com/kwebio/kweb-core/pulls

**Comment by alkoclick** [comment]
@sanity Is this still ongoing? We're about to switch over to https, I may be able to help out , but would like some general view on this. I feel like a plugin may be a nice way to tackle this

**Comment by sanity** [comment]
@alkoclick It would definitely be great if you could look at this as it's absolutely a requirement, and I haven't made any progress since creating this issue.  My sense is that this should just be a couple of hours.

A plugin might work, I'm not super-familiar with setting up HTTPS with Ktor so I'm not sure whether it can be done through the current plugin interface.

One thing I'm not sure of is the cleanest way to allow the programmer to provide the private SSL key for the domain.

**Comment by alkoclick** [comment]
I had a run at a working implem, feel free to take a look. Also my git keeps attacking the `build.gradle` file, I think it's because of CRLF

Giving more dev power over the Ktor configuration is definitely something I feel would be useful. And from what I saw, the Kweb class should definitely be broken down further (probably a ClientStateManager or similar component could help to take on all that functionality, then we could externalize the env config as well)

What is the motivation behind the Ktor configuration currently being abstracted away?

**Comment by sanity** [comment]
> I had a run at a working implem, feel free to take a look. 

Will do.

> Giving more dev power over the Ktor configuration is definitely something I feel would be useful

Open to suggestions on that.

> Giving more dev power over the Ktor configuration is definitely something I feel would be useful. And from what I saw, the Kweb class should definitely be broken down further (probably a ClientStateManager or similar component could help to take on all that functionality, then we could externalize the env config as well)

Yes, Kweb is definitely a god class and it needs to be broken up, it has been on my todo list for a long time: #58 :)

I think management of client state is definitely one component that could be refactored out.

> What is the motivation behind the Ktor configuration currently being abstracted away?

Hmm, not quite sure what you mean by "abstracted away" here, but generally much of the plugin system was build "on demand", so I'm open to ideas about how to improve it.

**Comment by sanity** [comment]
HTTPS is [now supported](https://github.com/kwebio/kweb-demos/blob/master/https/src/HttpsApp.kt).
