### ISSUE TITLE
there should be an easy way to set an element's class name

### ISSUE THREAD

**Issue by Benjozork** [kwebio/kweb-core#67]
currently, the only way to set an element's class name(s) is:
```kotlin
val messages = div(attributes = mapOf("class" to "message messages-container"))
```
or
```kotlin
val messages = div().addClasses("message", "messages-container")
```
which relies on a second client-side js call after the element is created

there should be a less crusty way to do this, perhaps adding a `class` optional parameter to the element builders ?
```kotlin
val messages = div(class = "message messages-container")
```
or more idiomatically:
```kotlin
val messages = div(classes = arrayOf("message", "messages-container"))
```
which should both add the classes during the SSR.

have a good day :)

**Comment by sanity** [comment]
Yeah, a more concise approach would be more elegant - although I'm not sure there will be a significant difference in efficiency behind the scenes due to various optimizations (now and in the pipeline).

The tricky part about adding an optional parameter to `div` is that, to be consistent, we'd need to add the same parameter to all of the other element constructors (`p`, `table`, etc), that's a lot of cutting and pasting.

If we renamed `Element.setClasses()` to `Element.classes()` then this would work:

```
val messages = div().classes("message", "messages-container")
```
Thoughts?

**Comment by sanity** [comment]
Oh, you probably saw but the Fomantic [plugin](https://docs.kweb.io/en/latest/style.html) has its own approach to allowing the style to be expressed concisely.

**Comment by Benjozork** [comment]
Your suggestion seems good ! Thank you :)
